# Generated by Django 5.1.4 on 2025-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
